apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.auth.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: {{ .Values.auth.image }}
        args:
          - "-text={{ .Values.auth.message }}"
        ports:
        - containerPort: {{ .Values.auth.port }}