apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: demo-ingress
  namespace: demo-microservices

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  rules:
    - host: demo.local
      http:
        paths:

          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth
                port:
                  number: 80

          - path: /portfolio
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  number: 80