apiVersion: apps/v1
kind: Deployment

metadata:
  name: portfolio
  namespace: demo-microservices

spec:
  replicas: 1

  selector:
    matchLabels:
      app: portfolio

  template:
    metadata:
      labels:
        app: portfolio

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: portfolio
          image: 320060061347.dkr.ecr.eu-north-1.amazonaws.com/portfolio:latest

          ports:
            - containerPort: 5000